version: '3.8'
name: sns

services:
  identity-service:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.identity-service
    container_name: sns.identity-service
    ports:
      - "8081:8081"
    volumes:
      - ./identity-service/logs:/app/logs
    environment:
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - sns-network
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: sns.postgres
    hostname: postgres
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    networks:
      - sns-network
    restart: unless-stopped
  
  mongodb:
    image: mongo
    container_name: sns.mongodb
    hostname: mongodb
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    volumes:
      - ./data/mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    networks:
      - sns-network
    restart: unless-stopped

  neo4j:
    image: neo4j
    container_name: sns.neo4j
    hostname: neo4j
    ports:
      - ${NEO4J_DB_HTTP_PORT}:${NEO4J_DB_HTTP_PORT}
      - ${NEO4J_DB_BOLT_PORT}:${NEO4J_DB_BOLT_PORT}
    volumes:
      - ./data/neo4j_data:/data
      - ./data/neo4j_logs:/logs
      - ./data/neo4j_plugins:/plugins
    environment:
      NEO4J_AUTH: ${NEO4J_DB_USERNAME}/${NEO4J_DB_PASSWORD}
    networks:
      - sns-network
    restart: unless-stopped
  
  kafka:
    image: 'bitnami/kafka'
    container_name: sns.kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094" 
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
    - sns-network
    restart: unless-stopped

networks:
  sns-network:
    driver: bridge
    name: sns-network
