version: '3.8'
name: sns

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api-gateway
    container_name: sns.api-gateway
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    env_file:
    - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - identity-service
    networks:
      - sns-network
    restart: unless-stopped

  identity-service:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.identity-service
    container_name: sns.identity-service
    expose:
      - ${IDENTITY_SERVICE_PORT}
    volumes:
      - ./identity-service/logs:/app/logs
    env_file:
    - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres
    networks:
      - sns-network
    restart: unless-stopped

  profile-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.profile-service
    container_name: sns.profile-service
    expose:
      - ${PROFILE_SERVICE_PORT}
    volumes:
      - ./profile-service/logs:/app/logs
    env_file:
    - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - neo4j
    networks:
      - sns-network
    restart: unless-stopped

  notification-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.notification-service
    container_name: sns.notification-service
    expose:
      - ${NOTIFICATION_SERVICE_PORT}
    volumes:
      - ./notification-service/logs:/app/logs
    env_file:
    - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - sns-network
    restart: unless-stopped

  post-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.post-service
    container_name: sns.post-service
    expose:
      - ${POST_SERVICE_PORT}
    volumes:
      - ./post-service/logs:/app/logs
    env_file:
    - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - sns-network
    restart: unless-stopped

  file-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.file-service
    container_name: sns.file-service
    expose:
      - ${FILE_SERVICE_PORT}
    volumes:
      - ./file-service/logs:/app/logs
    env_file:
    - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - sns-network
    restart: unless-stopped

  chat-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.chat-service
    container_name: sns.chat-service
    expose:
      - ${CHAT_SERVICE_PORT}
    volumes:
      - ./chat-service/logs:/app/logs
    env_file:
    - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - sns-network
    restart: unless-stopped

  search-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.search-service
    container_name: sns.search-service
    expose:
      - ${SEARCH_SERVICE_PORT}
    volumes:
      - ./search-service/logs:/app/logs
    env_file:
    - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - sns-network
    restart: unless-stopped

  postgres:
    image: postgres:18.0-alpine
    container_name: sns.postgres
    hostname: postgres
    ports:
      - ${IDENTITY_POSTGRES_DB_PORT}:${IDENTITY_POSTGRES_DB_PORT}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql
    env_file:
    - .env
    environment:
      POSTGRES_USER: ${IDENTITY_POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${IDENTITY_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${IDENTITY_POSTGRES_DB_NAME}
    networks:
      - sns-network
    restart: unless-stopped
  
  mongodb:
    image: mongo
    container_name: sns.mongodb
    hostname: mongodb
    ports:
      - ${NOTIFICATION_MONGO_DB_PORT}:${NOTIFICATION_MONGO_DB_PORT}
    volumes:
      - ./data/mongodb_data:/data/db
    env_file:
    - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${NOTIFICATION_MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${NOTIFICATION_MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${NOTIFICATION_MONGO_DB_NAME}
    networks:
      - sns-network
    restart: unless-stopped

  neo4j:
    image: neo4j
    container_name: sns.neo4j
    hostname: neo4j
    ports:
      - ${PROFILE_NEO4J_DB_HTTP_PORT}:${PROFILE_NEO4J_DB_HTTP_PORT}
      - ${PROFILE_NEO4J_DB_BOLT_PORT}:${PROFILE_NEO4J_DB_BOLT_PORT}
    volumes:
      - ./data/neo4j_data:/data
      - ./data/neo4j_logs:/logs
      - ./data/neo4j_plugins:/plugins
    env_file:
    - .env
    environment:
      NEO4J_AUTH: ${PROFILE_NEO4J_DB_USERNAME}/${PROFILE_NEO4J_DB_PASSWORD}
    networks:
      - sns-network
    restart: unless-stopped
  
  kafka:
    image: 'apache/kafka'
    container_name: sns.kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094" 
    env_file:
    - .env
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
    - sns-network
    restart: unless-stopped

networks:
  sns-network:
    driver: bridge
    name: sns-network
