name: sns

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api-gateway
    container_name: sns.api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8888"
    env_file:
    - .env.gateway
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - identity-service
    networks:
      - sns-network
    restart: unless-stopped

  identity-service:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.identity-service
    container_name: sns.identity-service
    expose:
      - "8080"
    volumes:
      - ./identity-service/logs:/app/logs
    env_file:
    - .env.identity
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres
    networks:
      - sns-network
    restart: unless-stopped

  profile-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.profile-service
    container_name: sns.profile-service
    expose:
      - "8081"
    volumes:
      - ./profile-service/logs:/app/logs
    env_file:
    - .env.profile
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - neo4j
    networks:
      - sns-network
    restart: unless-stopped

  notification-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.notification-service
    container_name: sns.notification-service
    expose:
      - "8082"
    volumes:
      - ./notification-service/logs:/app/logs
    env_file:
    - .env.notification
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongodb
      - kafka
    networks:
      - sns-network
    restart: unless-stopped

  post-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.post-service
    container_name: sns.post-service
    expose:
      - "8083"
    volumes:
      - ./post-service/logs:/app/logs
    env_file:
    - .env.post
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongodb
    networks:
      - sns-network
    restart: unless-stopped

  file-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.file-service
    container_name: sns.file-service
    expose:
      - "8084"
    volumes:
      - ./file-service/logs:/app/logs
    env_file:
    - .env.file
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongodb
    networks:
      - sns-network
    restart: unless-stopped

  chat-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.chat-service
    container_name: sns.chat-service
    expose:
      - "8085"
    volumes:
      - ./chat-service/logs:/app/logs
    env_file:
    - .env.chat
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mongodb
    networks:
      - sns-network
    restart: unless-stopped

  search-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.search-service
    container_name: sns.search-service
    expose:
      - "8086"
    volumes:
      - ./search-service/logs:/app/logs
    env_file:
    - .env.search
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - sns-network
    restart: unless-stopped

  postgres:
    image: postgres:18.0-alpine
    container_name: sns.postgres
    hostname: postgres
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql
    env_file:
    - .env.postgres
    networks:
      - sns-network
    restart: unless-stopped

  mongodb:
    image: bitnami/mongodb:latest
    container_name: sns.mongodb
    hostname: mongodb
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - ./data/mongodb_data:/bitnami/mongodb
      - ./init/mongodb:/docker-entrypoint-initdb.d
    env_file:
    - .env.mongo
    networks:
      - sns-network
    restart: unless-stopped

  neo4j:
    image: neo4j:5.26.18
    container_name: sns.neo4j
    hostname: neo4j
    ports:
      - "${NEO4J_DB_HTTP_PORT}:7474"
      - "${NEO4J_DB_BOLT_PORT}:7687"
    volumes:
      - ./data/neo4j_data:/data
      - ./data/neo4j_logs:/logs
      - ./data/neo4j_plugins:/plugins
    env_file:
    - .env.neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_DB_USERNAME}/${NEO4J_DB_PASSWORD}
    networks:
      - sns-network
    restart: unless-stopped
  
  kafka:
    image: 'apache/kafka:4.1.1'
    container_name: sns.kafka
    hostname: kafka
    ports:
      - "${KAFKA_CLIENT_PORT}:9092"
    expose:
      - "9093"
      - "9094"
    env_file:
    - .env.kafka
    networks:
    - sns-network
    restart: unless-stopped

networks:
  sns-network:
    driver: bridge
    name: sns-network
