# Stage 1: Build
FROM gradle:8.5-jdk21 AS build

WORKDIR /app

COPY chat-service/build.gradle ./
COPY chat-service/gradle.properties ./
COPY chat-service/settings.gradle ./
COPY chat-service/lombok.config ./
RUN gradle dependencies --no-daemon
COPY chat-service/src ./src
RUN gradle clean build -x test --no-daemon

# Stage 2: Run
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

ENV JAVA_OPTS="-Xmx512m -Xms256m"

ARG CHAT_SERVICE_PORT=8085
EXPOSE ${CHAT_SERVICE_PORT}

# Add user
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# Run the application
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar app.jar"]