# Stage 1: Build
FROM gradle:8.5-jdk21 AS build

WORKDIR /app

COPY api-gateway/gradle.properties ./
COPY api-gateway/settings.gradle ./
COPY api-gateway/build.gradle ./
COPY api-gateway/lombok.config ./
RUN gradle dependencies --no-daemon
COPY api-gateway/src ./src
RUN gradle clean build -x test --no-daemon

# Stage 2: Run
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

ENV JAVA_OPTS="-Xmx512m -Xms256m"

ARG API_GATEWAY_PORT=8888
EXPOSE ${API_GATEWAY_PORT}

# Add user
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# Run the application
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar app.jar"]