FROM gradle:8.5-jdk21-slim AS build
COPY --chown=gradle:gradle ../identity-service /app
WORKDIR /app

RUN gradle build --no-daemon

FROM openjdk:21-jre-slim

ENV PORT 8081

EXPOSE 8081

WORKDIR /app

COPY --from=build /app/build/libs/identity-service-0.0.1-SNAPSHOT.jar app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]